/**
 * `legacy-store` — an error-first callback API, the way Node wrote everything
 * before promises landed.
 *
 * It is typed, and the types are honest. That is the point of this exercise:
 * even an honest error-first signature CANNOT express the contract, because
 * `(error: Error | null, value?: T)` permits all four combinations while the
 * API only ever produces two — or, here, three.
 *
 * You do not edit this file.
 *
 *   loadRecord("r1")     -> (null, record)
 *   loadRecord("boom")   -> (new Error("store offline"))
 *   loadRecord("ghost")  -> (null, undefined)     <- neither. Yes, really.
 *
 *   searchRecords("in")  -> (null, [matches])     (an empty array when none)
 *   searchRecords("")    -> (new Error("term must not be empty"))
 */

export type StoredRecord = {
  readonly id: string;
  readonly name: string;
  readonly version: number;
};

const RECORDS: readonly StoredRecord[] = [
  { id: "r1", name: "Invoices", version: 3 },
  { id: "r2", name: "Contacts", version: 1 },
  { id: "r3", name: "Inventory", version: 7 },
];

export function loadRecord(
  id: string,
  done: (error: Error | null, record?: StoredRecord) => void,
): void {
  queueMicrotask(() => {
    if (id === "boom") {
      done(new Error("store offline"));
      return;
    }

    const found = RECORDS.find((record) => record.id === id);

    // An unknown id is not an error here — it calls back with nothing at all.
    done(null, found);
  });
}

export function searchRecords(
  term: string,
  done: (error: Error | null, matches?: readonly StoredRecord[]) => void,
): void {
  queueMicrotask(() => {
    if (term.length === 0) {
      done(new Error("term must not be empty"));
      return;
    }

    const needle = term.toLowerCase();
    done(
      null,
      RECORDS.filter((record) => record.name.toLowerCase().includes(needle)),
    );
  });
}
