/**
 * The typed boundary you built in 17/01, provided here so this exercise stands
 * alone. You do not edit this file.
 *
 * The only thing that matters for 17/02: `HttpResponse["body"]` is `unknown`.
 * The boundary has verified the ENVELOPE (there was a response, it had a
 * numeric status, it was not a 404) and nothing whatsoever about the payload.
 * Turning that `unknown` into a domain type is this exercise.
 */

import { createClient } from "./legacy-http";

/** The slice of `legacy-http` we actually use. Nothing more. */
export type LegacyRequestOptions = {
  readonly query?: Readonly<Record<string, string>>;
};

export type LegacyClient = {
  request(
    method: string,
    path: string,
    options?: LegacyRequestOptions,
  ): Promise<unknown>;
};

/** What our own code speaks in: a status, and a body nobody has vouched for. */
export type HttpResponse = {
  readonly status: number;
  readonly body: unknown;
};

export class HttpError extends Error {
  constructor(
    readonly status: number,
    readonly path: string,
    message: string,
  ) {
    super(message);
    // Subclassing Error does not set `name`; without this every stack trace
    // and every serialised log line just says "Error".
    this.name = "HttpError";
  }
}

export function isHttpError(value: unknown): value is HttpError {
  return value instanceof HttpError;
}

export function toHttpResponse(raw: unknown, path: string): HttpResponse {
  const malformed = (): never => {
    throw new HttpError(502, path, "malformed response");
  };

  // `typeof null === "object"` and arrays are objects too, so both need
  // rejecting explicitly.
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
    return malformed();
  }

  // `in` narrows an `object` to one that has the key, and the property then
  // reads as `unknown` — which is exactly enough to check it, with no cast.
  if (!("statusCode" in raw)) return malformed();

  const status: unknown = raw.statusCode;
  if (typeof status !== "number" || !Number.isFinite(status)) {
    return malformed();
  }

  // A 204 has no payload at all; that is not an error.
  const body: unknown = "payload" in raw ? raw.payload : undefined;

  return { status, body };
}

export function toHttpError(reason: unknown, path: string): HttpError {
  // Already normalised — do not wrap it twice and lose the status.
  if (isHttpError(reason)) return reason;

  // The library rejects with a bare string on a transport failure.
  if (typeof reason === "string") return new HttpError(0, path, reason);

  if (reason instanceof Error) return new HttpError(0, path, reason.message);

  if (typeof reason === "object" && reason !== null && "statusCode" in reason) {
    const status: unknown = reason.statusCode;

    if (typeof status === "number") {
      const detail: unknown = "error" in reason ? reason.error : undefined;
      return new HttpError(
        status,
        path,
        typeof detail === "string" ? detail : "request failed",
      );
    }
  }

  // `throw 0`, `throw null`, a rejected promise of a Symbol — all possible.
  return new HttpError(0, path, "unknown transport failure");
}

export type TypedClient = {
  get(
    path: string,
    query?: Readonly<Record<string, string>>,
  ): Promise<HttpResponse>;
};

export function createTypedClient(legacy: LegacyClient): TypedClient {
  return {
    async get(path, query) {
      let raw: unknown;

      try {
        // Under exactOptionalPropertyTypes, `{ query }` with an undefined
        // `query` does NOT satisfy `query?: …`. Build the object instead.
        raw = await legacy.request(
          "GET",
          path,
          query === undefined ? {} : { query },
        );
      } catch (reason) {
        // Every rejection shape becomes one error type, here and nowhere else.
        throw toHttpError(reason, path);
      }

      const response = toHttpResponse(raw, path);

      // Belt and braces: the library rejects 4xx/5xx, but a resolved error
      // status would otherwise sail past as if it were data.
      if (response.status >= 400) {
        throw new HttpError(
          response.status,
          path,
          `request failed with status ${response.status}`,
        );
      }

      return response;
    },
  };
}

export function connect(baseUrl: string, flakyTimes = 0): TypedClient {
  // THE boundary line. `createClient` returns `any`; this annotation is what
  // stops that `any` propagating into everything it touches. From here on the
  // compiler is back in charge.
  const legacy: LegacyClient = createClient({ baseUrl, flakyTimes });

  return createTypedClient(legacy);
}
