/**
 * `legacy-http` — the untyped dependency.
 *
 * Pretend this arrived from `node_modules`: a popular little HTTP helper whose
 * author never shipped types, and whose `@types/legacy-http` package is three
 * major versions out of date. Every signature here is `any`, so TypeScript will
 * happily let you write `client.reqeust(...)` and find out at runtime.
 *
 * You do not edit this file. Your job in this section is to build a boundary
 * around it so that the `any` stops here.
 *
 * Its actual (undocumented) behaviour:
 *
 *   createClient({ baseUrl, flakyTimes? })
 *     -> { request(method, path, options?), stats() }
 *
 *   request resolves with  { statusCode, payload, headers }
 *   request REJECTS with   { statusCode, error }   for 4xx/5xx  (not an Error!)
 *   request REJECTS with   "socket hang up"        for the first `flakyTimes`
 *                                                   calls        (a string!)
 *
 * The payloads are snake_case wire shapes, not your domain model.
 */

const PRODUCTS: any[] = [
  {
    id: "p1",
    title: "Mechanical keyboard",
    price_cents: 8999,
    tags: ["input", "desk"],
    discontinued: false,
  },
  {
    id: "p2",
    title: "Wireless mouse",
    price_cents: 3499,
    tags: ["input", "wireless"],
  },
  {
    id: "p3",
    title: "27-inch monitor",
    price_cents: 24900,
    tags: ["display"],
    discontinued: false,
  },
  {
    id: "p4",
    title: "USB-C hub",
    price_cents: 5900,
    tags: ["desk"],
    discontinued: true,
  },
  {
    id: "p5",
    title: "Desk lamp",
    price_cents: 4200,
    tags: ["desk"],
  },
];

function page(cursor: any, limit: any): any {
  const start: any = Number.parseInt(String(cursor ?? "0"), 10) || 0;
  const size: any = Number.parseInt(String(limit ?? "2"), 10) || 2;
  const items: any = PRODUCTS.slice(start, start + size);
  const next: any = start + size;

  return {
    items,
    next_cursor: next < PRODUCTS.length ? String(next) : null,
  };
}

export function createClient(options: any): any {
  const flakyTimes: any = options?.flakyTimes ?? 0;
  let calls = 0;
  let flakesLeft = flakyTimes;

  return {
    baseUrl: options?.baseUrl,

    stats(): any {
      return { calls };
    },

    request(method: any, path: any, requestOptions: any): any {
      calls += 1;

      if (flakesLeft > 0) {
        flakesLeft -= 1;
        // Rejecting with a bare string. Yes, really.
        return Promise.reject("socket hang up");
      }

      if (method !== "GET") {
        return Promise.reject({
          statusCode: 405,
          error: "method not allowed",
        });
      }

      const query: any = requestOptions?.query ?? {};

      if (path === "/products") {
        return Promise.resolve({
          statusCode: 200,
          headers: { "content-type": "application/json" },
          payload: page(query.cursor, query.limit),
        });
      }

      if (String(path).startsWith("/products/")) {
        const id: any = String(path).slice("/products/".length);
        const found: any = PRODUCTS.find((product: any) => product.id === id);

        if (found === undefined) {
          return Promise.reject({ statusCode: 404, error: "no such product" });
        }

        return Promise.resolve({
          statusCode: 200,
          headers: { "content-type": "application/json" },
          payload: found,
        });
      }

      return Promise.reject({ statusCode: 404, error: "no such route" });
    },
  };
}
