/**
 * `vendor-flags` — the untyped dependency.
 *
 * Pretend this is `node_modules/@vendor/flags/index.js` plus the declaration
 * file its author generated in a hurry: every signature is `any`, so TypeScript
 * will let you write anything at all about what comes back.
 *
 * `any` is legal here and nowhere else in this exercise. That asymmetry is the
 * exercise: the dependency is what it is, and your job is to make sure the
 * `any` gets no further than one function.
 *
 * You do not edit this file. Its actual, undocumented behaviour:
 *
 *   fetchFlag(key)         -> { key, value, updated_at }  |  null
 *   fetchAllFlags()        -> an array that also contains junk entries
 *   writeFlag(key, value)  -> { ok: 1 }  |  { ok: 0, error: "unknown flag" }
 *                           -> "accepted"   for "beta.banner", which is still
 *                                           served by an older endpoint
 *
 * Note `ok: 1`. It is a number, and the vendor's docs call it a boolean.
 */

const FLAGS: any[] = [
  { key: "checkout.v2", value: true, updated_at: "2026-01-05" },
  { key: "search.fuzzy", value: false, updated_at: "2025-11-20" },
  { key: "beta.banner", value: true, updated_at: "2026-02-14" },
];

export function fetchFlag(key: any): any {
  const found: any = FLAGS.find((flag: any) => flag.key === key);
  return found === undefined ? null : { ...found };
}

export function fetchAllFlags(): any {
  return [
    ...FLAGS.map((flag: any) => ({ ...flag })),
    // A half-written record the vendor's own migration left behind.
    { key: "legacy.mode" },
    // And whatever this is.
    "beta.banner",
    null,
  ];
}

export function writeFlag(key: any, value: any): any {
  const found: any = FLAGS.find((flag: any) => flag.key === key);

  if (found === undefined) {
    return { ok: 0, error: "unknown flag" };
  }

  if (key === "beta.banner") {
    // This one is still served by the endpoint that predates the { ok }
    // envelope. Nobody documented it, and nobody is going to.
    return "accepted";
  }

  // The real SDK would send this to a service. Here the write is a no-op, so
  // that the tests cannot depend on each other's order.
  void value;
  return { ok: 1 };
}
