/**
 * A tiny module that exports BOTH a type and a value.
 *
 * That combination is the whole reason `isolatedModules` exists: a single-file
 * transpiler reading `exercise.ts` has never seen this file, so it cannot know
 * which of the two names is erased at compile time and which one survives.
 *
 * You do not edit this file.
 */

export type Shape =
  | { readonly kind: "circle"; readonly radius: number }
  | { readonly kind: "square"; readonly side: number };

export type ShapeKind = Shape["kind"];

export function area(shape: Shape): number {
  return shape.kind === "circle"
    ? Math.PI * shape.radius ** 2
    : shape.side ** 2;
}
