/**
 * `legacy-slug` — the untyped dependency.
 *
 * Pretend this came out of `node_modules`: plain JavaScript, no types, no
 * `@types/legacy-slug` on npm, and a README that is three years out of date.
 *
 * You do not edit this file. Read it, though — its ACTUAL behaviour is the only
 * specification you have, and one of these functions does not do what its name
 * suggests.
 */

function slugify(input) {
  return String(input)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function truncate(input, max) {
  const text = String(input);
  return text.length <= max ? text : `${text.slice(0, max)}...`;
}

/**
 * Splits a comma-separated list.
 *
 * Undocumented: returns `undefined` — not `[]` — when there is nothing to
 * split. Two thousand packages do something like this.
 */
function tags(csv) {
  const parts = String(csv)
    .split(",")
    .map((part) => part.trim())
    .filter((part) => part.length > 0);

  return parts.length === 0 ? undefined : parts;
}

// A vendor script announcing itself on the global object, the way half the
// analytics and widget scripts in the world do.
globalThis.__LEGACY_SLUG__ = { version: "1.4.0", installedAt: "2019-04-02" };

export default { slugify, truncate, tags, VERSION: "1.4.0" };
