/**
 * The declaration file for `legacy-slug.js`.
 *
 * This is the whole mechanism: a `.d.ts` sitting next to a `.js` file, saying
 * what the JavaScript contains. TypeScript reads it, emits nothing from it, and
 * trusts every word.
 *
 * In a real project you would write the shape out here, or in a
 * `declare module "legacy-slug" { … }` block under `src/types/`:
 *
 *   declare module "legacy-slug" {
 *     export function slugify(input: string): string;
 *     …
 *   }
 *
 * In this exercise the shape lives in `exercise.ts` instead, so the test can
 * grade it — that is the only artificial thing here. You do not edit this file.
 */

import type { LegacySlug } from "./exercise";

declare const legacySlug: LegacySlug;

export default legacySlug;
